### ISSUE TITLE
add method to set balance of impersonated acc in mainnet-fork

### ISSUE THREAD

**Issue by bout3fiddy** [ApeWorX/ape-foundry#26]
### Overview

Provide methods for setting eth/native token balance of any address.

### Specification

```
acc = ape.account[0x...]
acc.balance += 10**18
```

**Comment by unparalleled-js** [comment]
https://github.com/ApeWorX/ape-foundry/blob/main/ape_foundry/providers.py#L295

**Comment by fubuloubu** [comment]
Sorry about the confusion
