### ISSUE TITLE
feat: host should be usable with a environment variable in ape-config.yaml for foundry [APE-1191]

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape-foundry#62]
### Overview

Provide a simple overview of what you wish to see added. Please include:

- What you are trying to do
I am trying to use docker containers so i need to programmatically set the host IP
- Why Ape's current functionality is inadequate to address your goal
currently it is required to set the host in the ape-config yaml and that is not able to be modified at runtime without rebuilding my docker image

### Specification

make host: in ape-config.yaml be available to be populated from an environment variable

### Dependencies

n/a

**Comment by antazoey** [comment]
Would be solved by this https://github.com/ApeWorX/ape/issues/292
