### ISSUE TITLE
Transactions fail requiring funds for gas when impersonating smart contracts (version 0.7.3 only)

### ISSUE THREAD

**Issue by rockorama** [ApeWorX/ape-foundry#90]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.7.10

$ ape plugins list
Installed Plugins
  foundry    0.7.3
  vyper      0.7.0
```

* Python 3.10.0
* OS: macOS

### What went wrong?

After upgrading from ape-foundry 0.7.2 to 0.7.3 I started getting the error `Insufficient funds for gas * price + value` when impersonating smart-contracts from tests. The error makes sense, because the contracts don't have any eth, but it used to work normally in prior versions.

![image](https://uploads.linear.app/ad7c7699-1d2a-44e2-9cc9-caacb0bf9077/4a7ac3cd-12df-4a72-a2a1-8c1aa8d15d38/96c9980c-f9b1-4c85-b751-f81254a2b2af?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FkN2M3Njk5LTFkMmEtNDRlMi05Y2M5LWNhYWNiMGJmOTA3Ny80YTdhYzNjZC0xMmRmLTRhNzItYTJhMS04YzFhYThkMTVkMzgvOTZjOTk4MGMtZjliMS00Yzg1LWI3NTEtZjgxMjU0YTJiMmFmIiwiaWF0IjoxNzE4MzAwODg3LCJleHAiOjMzMjg4ODYwODg3fQ.XYeJWQt_Q-PbIiaTSZie7p7as39qZgcBbhgHy93M4g4)

![image](https://uploads.linear.app/ad7c7699-1d2a-44e2-9cc9-caacb0bf9077/4283f5c2-138e-4f66-8830-429f0abc6c22/b03dd823-1d6f-475c-a36d-f7f4dab8e7c4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FkN2M3Njk5LTFkMmEtNDRlMi05Y2M5LWNhYWNiMGJmOTA3Ny80MjgzZjVjMi0xMzhlLTRmNjYtODgzMC00MjlmMGFiYzZjMjIvYjAzZGQ4MjMtMWQ2Zi00NzVjLWEzNmQtZjdmNGRhYjhlN2M0IiwiaWF0IjoxNzE4MzAwODg3LCJleHAiOjMzMjg4ODYwODg3fQ.xvE1EzToe6GuRRebKYZRvgR4ShxDHzZiNkIMFQQsCbQ)

![image](https://uploads.linear.app/ad7c7699-1d2a-44e2-9cc9-caacb0bf9077/4ad377aa-cd42-401d-8ba0-b5af3cb7003b/9a469db2-1889-4d03-9755-b8df1187c470?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FkN2M3Njk5LTFkMmEtNDRlMi05Y2M5LWNhYWNiMGJmOTA3Ny80YWQzNzdhYS1jZDQyLTQwMWQtOGJhMC1iNWFmM2NiNzAwM2IvOWE0NjlkYjItMTg4OS00ZDAzLTk3NTUtYjhkZjExODdjNDcwIiwiaWF0IjoxNzE4MzAwODg3LCJleHAiOjMzMjg4ODYwODg3fQ.qOajFYh8vvWh3xIrTJ6cd4AyKs7Qkgchme09bGnyEu4)

![image](https://uploads.linear.app/ad7c7699-1d2a-44e2-9cc9-caacb0bf9077/e164284d-28c3-45f3-8dbb-db64364c8f52/55199bb1-8350-43e9-9677-9b154ad4855d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FkN2M3Njk5LTFkMmEtNDRlMi05Y2M5LWNhYWNiMGJmOTA3Ny9lMTY0Mjg0ZC0yOGMzLTQ1ZjMtOGRiYi1kYjY0MzY0YzhmNTIvNTUxOTliYjEtODM1MC00M2U5LTk2NzctOWIxNTRhZDQ4NTVkIiwiaWF0IjoxNzE4MzAwODg3LCJleHAiOjMzMjg4ODYwODg3fQ.Iqy3QdYdnY959pH6zxtIrRub2IXhYQKUjE-6bcY-UM4)

![image](https://uploads.linear.app/ad7c7699-1d2a-44e2-9cc9-caacb0bf9077/adcb3a49-f335-4095-9a9d-5e1694c8c37b/77b314cd-99b3-46eb-87aa-bef4dbab38ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FkN2M3Njk5LTFkMmEtNDRlMi05Y2M5LWNhYWNiMGJmOTA3Ny9hZGNiM2E0OS1mMzM1LTQwOTUtOWE5ZC01ZTE2OTRjOGMzN2IvNzdiMzE0Y2QtOTliMy00NmViLTg3YWEtYmVmNGRiYWIzOGNlIiwiaWF0IjoxNzE4MzAwODg3LCJleHAiOjMzMjg4ODYwODg3fQ.V5UeJ6LkaVA_lfnLtRhM54fulqZQbB4XbjS08v843E4)

**Comment by antazoey** [comment]
Yes, it no longer is going to work, you have to set balances now for accounts. This is because of some checks in ape core and changes to fee settings.

Alternatively, if you want it to just work like it before you can set the fees all to 0 in the config, but that is not as ideal imo.

I think it makes more sense to ensure you accounts have  balances before spending money in tests:

```
account.balance += 100_000_000_000_000
```
